### ISSUE TITLE
Could not find definition of HEAP_CHECK_SIZE

### ISSUE THREAD

**Issue by anasnest** [wolfSSL/wolfssl-freertos#4]
It is used in https://github.com/wolfSSL/wolfssl-freertos/blob/659d06ecf0969b1b77965e7170f504e9375cacc3/FreeRTOS-Classic/FreeRTOS/Source/portable/MemMang/heap_4.c

But nowhere it is defined

**Comment by dgarske** [comment]
@anasnest , the `pvPortRealloc` function is not standard and I added it with PR https://github.com/wolfSSL/wolfssl-freertos/pull/3. However the `HEAP_CHECK_SIZE` should be removed. I put up a fix to remove the `HEAP_CHECK_SIZE` here: 
https://github.com/wolfSSL/wolfssl-freertos/pull/5

Thanks, David Garske, wolfSSL
